### PR TITLE
I've come to bless you with something called math

### PR DESCRIPTION
**Pull request by DeDiamondPro**

### CODE REVIEW

**Comment by DeDiamondPro** [comment]
Also SimplyfyNumber is broken since in -lvl bushbot shows level 78 to have 7.88k xp while it actually has 306150 xp

**Comment by DeDiamondPro** [comment]
> Also SimplyfyNumber is broken since in -lvl bushbot shows level 78 to have 7.88k xp while it actually has 306150 xp 

Nvm that's to next and not total I'm stupid ignore me

**Comment by Ascynx** [comment]
wtf math

**Comment by IRONM00N** [comment]
too much math

**Comment by DeDiamondPro** [comment]
@IRONM00N I wrote a quick script that compares the things and I found that level to xp is identical but xp to level is not if the xp needed for a level is exactly identical to the xp given to the function, the old approach would return a lower level then it should return while the new one returns the correct amount.
Example: level 32 requires 52000 xp, when given 52000 xp the old function returns 31 while the new one returns 32
Full log: [https://hst.sh/gekacavige.makefile](https://hst.sh/gekacavige.makefile)
Code to compare:
```js
function convertXpToLevelOld(xp) {
    let i = 0;
    while (convertLevelToXpOld(i + 1) < xp) {
        i++;
    }
    return i;
}

function convertLevelToXpOld(level) {
    let xp = 0;
    for (let i = 0; i < level; i++) {
        xp += 100 * i + 75;
    }
    return xp;
}

function convertXpToLevelNew(xp) {
    return Math.floor((-25 + Math.sqrt(625 + 200 * xp)) / 100);
}

function convertLevelToXpNew(level) {
    return 50 * level * level + 25 * level; // 50x² + 25x
}

for (let i = 0; i <= 1000; i++) {
    const oldVal = convertLevelToXpOld(i);
    const newVal = convertLevelToXpNew(i);
    console.log(`level: ${i}, oldXp: ${oldVal}, newXp: ${newVal}`);
    if(oldVal !== newVal) throw "No match!"
}

for (let i = 0; i <= 2000000; i += 1000) {
    const oldVal = convertXpToLevelOld(i);
    const newVal = convertXpToLevelNew(i);
    console.log(`xp: ${i}, oldLevel: ${oldVal}, newLevel: ${newVal}`);
    if(oldVal !== newVal) console.log(`Level mismatch, XP needed for old: ${convertLevelToXpOld(oldVal)}, XP needed for new ${convertLevelToXpOld(newVal)}`)
}
```

**Review by IRONM00N — APPROVED** [review]
lgtm

**Comment by TymanWasTaken** [comment]
I was curious so I tested it
image

**Comment by DeDiamondPro** [comment]
> I was curious so I tested it
> image

So speed

**Pull request merged**
